spring:
  application:
    name: springboot-ai-gemini
  ai:
    vertex:
      ai:
        gemini:
          project-id: gen-lang-client-0759887745
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash-001